'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  Yolo:
    resources:
      instance-type: P5000
    needs:
      - CloneRepo
    uses: script@v1
    with:
      script: |-
        python3 /inputs/repo/hello.py
        python3 train.py --img 640 --cfg yolov5s.yaml --hyp /inputs/repo/hyp.scratch.yaml --batch 8 --epochs 50 --data /inputs/repo/thumb.yaml --weights yolov5s.pt --workers 24 --name thumb
        cp yolov5/runs /outputs/results/
      image: ultralytics/yolov5
    inputs:
      repo: CloneRepo.outputs.repo
      thumb:
        type: dataset
        with:
          ref: dsfbox6kwvcwmtj
    outputs:
      results:
        type: dataset
          with:
            ref: def123ghi456jkt