'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  HelloWorld:
    resources:
      instance-type: C5
    needs:
      - CloneRepo
    uses: script@v1
    with:
      script: pip install -r requirements.txt

      image: ultralytics/yolov5
    inputs:
      repo: CloneRepo.outputs.repo
      demo-dataset:
        type: dataset
        with:
          ref: ds4r0a0xnoizszj
    outputs:
      my-volume:
        type: volume