'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/sonicpierre/Yolo_pipeline.git
      
  Yolo:
    resources:
      instance-type: P5000
    needs:
      - CloneRepo
    uses: script@v1
    with:
      script: |-
        python3 /inputs/repo/training_part_yolo/train_yolo.py
        cp -r runs /outputs/volumeweights/
      image: ultralytics/yolov5
    inputs:
      repo: CloneRepo.outputs.repo
      mythumb:
        type: dataset
        with:
          ref: dsan9disnqrb1e7
    outputs:
      volumeweights:
        type: volume

  Tensorboard:
    resources:
      instance-type: P5000
    needs:
      - CloneRepo
    uses: script@v1
    with:
      script: |-
        echo Coucou
        git clone https://github.com/tensorflow/models.git
      image: paperspace/gradient-base:tf29-pt112-py39-2022-06-29
    inputs:
      repo: CloneRepo.outputs.repo
      mythumb:
        type: dataset
        with:
          ref: dsan9disnqrb1e7
    outputs:
      volumeweights:
        type: volume

  TestResult:
    resources:
      instance-type: P5000
    needs:
      - Yolo
    uses: script@v1
    with:
      script: |-
        python3 detect.py --source /inputs/mythumb/images/test/ --weights /inputs/volumeweights/runs/train/thumb/weights/best.pt --conf 0.25 --name thumb_det
        cp -r runs/detect /outputs/demo-dataset/
        python3 export.py --weights /inputs/volumeweights/runs/train/thumb/weights/best.pt --include torchscript onnx
        cp /inputs/volumeweights/runs/train/thumb/weights/best.onnx /outputs/demo-dataset/
        cp /inputs/volumeweights/runs/train/thumb/weights/best.pt /outputs/demo-dataset/
      image: ultralytics/yolov5
    inputs:
      volumeweights: Yolo.outputs.volumeweights
      mythumb:
        type: dataset
        with:
          ref: dsan9disnqrb1e7
    outputs:
      demo-dataset:
        type: dataset
        with:
          ref: ds4r0a0xnoizszj