'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/sonicpierre/Yolo_pipeline.git
  CloneTF:
    resources:
      instance-type: C5
    outputs:
      repomodels:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/tensorflow/models.git
  
  ConcertYoloVoc:
    resources:
      instance-type: C5
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
      mythumb:
        type: dataset
        with:
          ref: dsan9disnqrb1e7
    outputs:
      cvtmythumb:
        type: volume
    uses: script@v1
    with:
      script: |-
        pip install lxml --upgrade
        python /inputs/repo/training_part_tf/converter_yolo_voc.py
      image: paperspace/gradient-base:tf29-pt112-py39-2022-06-29

  Tensorflow:
    resources:
      instance-type: C5
    needs:
      - CloneRepo
      - CloneTF
      - ConcertYoloVoc
    inputs:
      repo: CloneRepo.outputs.repo
      repomodels: CloneTF.outputs.repomodels
      cvtmythumb: ConcertYoloVoc.outputs.cvtmythumb
      mythumb:
        type: dataset
        with:
          ref: dsan9disnqrb1e7
    outputs:
      cvtmythumb:
        type: volume
    uses: script@v1
    with:
      script: |-
        chmod +x /inputs/repo/training_part_tf/install_env.sh
        ./inputs/repo/training_part_tf/install_env.sh

        mkdir -p workspace/pre-trained-models
        wget http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz
        mv 'ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz' 'workspace/pre-trained-models'
        cd 'workspace/pre-trained-models' && tar -zxvf 'ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz'

      image: paperspace/gradient-base:tf29-pt112-py39-2022-06-29