'on':
  github:
    branches:
      only: main
      
jobs:
  CloneRepo:
    resources:
      instance-type: P5000
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/sonicpierre/Yolo_pipeline.git
  CloneTF:
    resources:
      instance-type: P5000
    outputs:
      repomodels:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/tensorflow/models.git
  
  ConvertYoloVoc:
    resources:
      instance-type: P5000
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
      mythumb:
        type: dataset
        with:
          ref: dsan9disnqrb1e7
    outputs:
      cvtmythumb:
        type: volume
    uses: script@v1
    with:
      script: |-
        pip install lxml --upgrade
        python /inputs/repo/training_part_tf/converter_yolo_voc.py
        
      image: paperspace/gradient-base:tf29-pt112-py39-2022-06-29

  ConvertVocTFrecord:
    resources:
      instance-type: P5000
    needs:
      - CloneRepo
      - ConvertYoloVoc
      - CloneTF
    inputs:
      repo: CloneRepo.outputs.repo
      repomodels: CloneTF.outputs.repomodels
      cvtmythumb: ConvertYoloVoc.outputs.cvtmythumb
      mythumb:
        type: dataset
        with:
          ref: dsan9disnqrb1e7
    outputs:
      tfrecordsmythumb:
        type: volume

    uses: script@v1
    with:
      script: |-
        cd /inputs/repomodels/research && protoc object_detection/protos/*.proto --python_out=. && cp object_detection/packages/tf2/setup.py . && python3 -m pip install .
        cd

        python3 /inputs/repo/training_part_tf/create_labelmap.py
        python3 /inputs/repo/training_part_tf/converter_voc_tfrecords.py -x /inputs/cvtmythumb/outputs/train -l /outputs/tfrecordsmythumb/labelmap.pbtxt -o /outputs/tfrecordsmythumb/train.record
        python3 /inputs/repo/training_part_tf/converter_voc_tfrecords.py -x /inputs/cvtmythumb/outputs/val -l /outputs/tfrecordsmythumb/labelmap.pbtxt -o /outputs/tfrecordsmythumb/val.record
        python3 /inputs/repo/training_part_tf/converter_voc_tfrecords.py -x /inputs/cvtmythumb/outputs/test -l /outputs/tfrecordsmythumb/labelmap.pbtxt -o /outputs/tfrecordsmythumb/test.record

      image: sonicpierre/tf_object_detection

  DownloadModel:
    resources:
      instance-type: P5000
    outputs:
      mymodel:
        type: volume
    uses: script@v1
    with:
      script: |-
        mkdir -p workspace/pre-trained-models
        wget http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz
        mv 'ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz' 'workspace/pre-trained-models'
        tar -zxvf 'workspace/pre-trained-models/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz'
        cp -R ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8 /outputs/mymodel

      image: paperspace/gradient-base:tf29-pt112-py39-2022-06-29

  Tensorflow:
    resources:
      instance-type: P5000
    needs:
      - CloneRepo
      - CloneTF
      - ConvertVocTFrecord
      - DownloadModel
    inputs:
      repo: CloneRepo.outputs.repo
      repomodels: CloneTF.outputs.repomodels
      tfrecordsmythumb: ConvertVocTFrecord.outputs.tfrecordsmythumb
      mymodel: DownloadModel.outputs.mymodel
      mythumb:
        type: dataset
        with:
          ref: dsan9disnqrb1e7
    outputs:
      resulttf:
        type: dataset
        with:
          ref: ds7izfjqcbci4d1
    uses: script@v1
    with:
      script: |-
        chmod +x /inputs/repo/training_part_tf/install_env.sh
        ./inputs/repo/training_part_tf/install_env.sh

        python3 /inputs/repo/training_part_tf/config_pipeline.py
        python3 /inputs/repomodels/research/object_detection/model_main_tf2.py --model_dir=/outputs/resulttf/model_res --pipeline_config_path=pipeline.config

      image: tensorflow/tensorflow:latest-gpu

