'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/sonicpierre/Yolo_pipeline.git
  CloneTF:
    resources:
      instance-type: C5
    outputs:
      repomodels:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/tensorflow/models.git
  
  Tensorflow:
    resources:
      instance-type: C5
    needs:
      - CloneRepo
      - CloneTF
    inputs:
      repo: CloneRepo.outputs.repo
      repomodels: CloneTF.outputs.repomodels
    uses: script@v1
    with:
      script: |-
        ls /inputs/repomodels/research/object_detection/protos/
        chmod +x /inputs/repo/training_part_tf/install_env.sh
        ./inputs/repo/training_part_tf/install_env.sh
        protoc /inputs/repomodels/research/object_detection/protos/*.proto --python_out=. && cp /inputs/repomodels/research/object_detection/packages/tf2/setup.py . && python -m pip install .
        python /inputs/repomodels/research/object_detection/builders/model_builder_tf2_test.py
        pip install tensorflow --upgrade

        wget http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz
        mv 'ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz' 'workspace/pre-trained-models'
        cd 'workspace/pre-trained-models' && tar -zxvf 'ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz'
        ls

        python /inputs/repo/training_part_tf/object_hello.py
      image: paperspace/gradient-base:tf29-pt112-py39-2022-06-29