'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/sonicpierre/Yolo_pipeline.git
  CloneTF:
    resources:
      instance-type: C5
    outputs:
      repomodels:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/tensorflow/models.git
  
  ConvertYoloVoc:
    resources:
      instance-type: C5
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
      mythumb:
        type: dataset
        with:
          ref: dsan9disnqrb1e7
    outputs:
      cvtmythumb:
        type: volume
    uses: script@v1
    with:
      script: |-
        pip install lxml --upgrade
        python /inputs/repo/training_part_tf/converter_yolo_voc.py

        ls /outputs/cvtmythumb/

        cp -R /inputs/mythumb/images/train/ /outputs/cvtmythumb/outputs/train
        cp -R /inputs/mythumb/images/val/ /outputs/cvtmythumb/outputs/val
        cp -R /inputs/mythumb/images/test/ /outputs/cvtmythumb/outputs/test
        
      image: paperspace/gradient-base:tf29-pt112-py39-2022-06-29

  ConvertVocTFrecord:
    resources:
      instance-type: C5
    needs:
      - CloneRepo
      - ConvertYoloVoc
      - CloneTF
    inputs:
      repo: CloneRepo.outputs.repo
      repomodels: CloneTF.outputs.repomodels
      cvtmythumb: ConvertYoloVoc.outputs.cvtmythumb
      mythumb:
        type: dataset
        with:
          ref: dsan9disnqrb1e7
    outputs:
      tfrecordsmythumb:
        type: volume
      debugger:
        type: dataset
        with:
          ref: dsqziuv60ua94yv

    uses: script@v1
    with:
      script: |-
        chmod +x /inputs/repo/training_part_tf/install_env.sh
        ./inputs/repo/training_part_tf/install_env.sh

        python /inputs/repo/training_part_tf/create_labelmap.py
        python /inputs/repo/training_part_tf/converter_voc_tfrecords.py -x /inputs/cvtmythumb/outputs/train -l /outputs/tfrecordsmythumb/labelmap.pbtxt -o /outputs/debugger/train.record
        python /inputs/repo/training_part_tf/converter_voc_tfrecords.py -x /inputs/cvtmythumb/outputs/val -l /outputs/tfrecordsmythumb/labelmap.pbtxt -o /outputs/debugger/val.record
        python /inputs/repo/training_part_tf/converter_voc_tfrecords.py -x /inputs/cvtmythumb/outputs/test -l /outputs/tfrecordsmythumb/labelmap.pbtxt -o /outputs/debugger/test.record

      image: paperspace/gradient-base:tf29-pt112-py39-2022-06-29

  DownloadModel:
    resources:
      instance-type: C5
    outputs:
      mymodel:
        type: volume
    uses: script@v1
    with:
      script: |-
        mkdir -p workspace/pre-trained-models
        wget http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz
        mv 'ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz' 'workspace/pre-trained-models'
        tar -zxvf 'workspace/pre-trained-models/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz'
        cp -R ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8 /outputs/mymodel

      image: paperspace/gradient-base:tf29-pt112-py39-2022-06-29

  Tensorflow:
    resources:
      instance-type: A4000
    needs:
      - CloneRepo
      - CloneTF
      - ConvertVocTFrecord
      - DownloadModel
    inputs:
      repo: CloneRepo.outputs.repo
      repomodels: CloneTF.outputs.repomodels
      tfrecordsmythumb: ConvertVocTFrecord.outputs.tfrecordsmythumb
      mymodel: DownloadModel.outputs.mymodel
      mythumb:
        type: dataset
        with:
          ref: dsan9disnqrb1e7
    outputs:
      cvtmythumb:
        type: volume
    uses: script@v1
    with:
      script: |-
        chmod +x /inputs/repo/training_part_tf/install_env.sh
        ./inputs/repo/training_part_tf/install_env.sh
        pip install numpy --upgrade
        mkdir model_res

        python /inputs/repo/training_part_tf/config_pipeline.py
        python /inputs/repomodels/research/object_detection/model_main_tf2.py --model_dir=model_res --pipeline_config_path=pipeline.config

      image: paperspace/gradient-base:tf29-pt112-py39-2022-06-29